export const INVALIDATE_ADMIN_LOGIN = 'admin/INVALIDATE_ADMIN_LOGIN';
export const REQUEST_ADMIN_LOGIN = 'admin/REQUEST_ADMIN_LOGIN';
export const RECEIVE_ADMIN_LOGIN_SUCCESS = 'admin/RECEIVE_ADMIN_LOGIN_SUCCESS';
export const REQUEST_ADMIN_LOGIN_FAILURE = 'admin/REQUEST_ADMIN_LOGIN_FAILURE';