export const REQUEST_AUCTIONS = 'auction/REQUEST_AUCTION';
export const REQUEST_AUCTIONS_FAILURE = 'auction/REQUEST_AUCTION_FAILURE';
export const RECEIVE_AUCTIONS_SUCCESS = 'auction/REQUEST_AUCTION_SUCCESS';

export const ADD_AUCTION = 'auction/ADD_AUCTION';
export const ADD_AUCTION_FAILURE = 'auction/ADD_AUCTION_FAILURE';
export const ADD_AUCTION_SUCCESS = 'auction/ADD_AUCTION_SUCCESS';